import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// AIInteriorDesign — generated by AppFactoryKit appgen from niche "ai-interior-design".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum AIInteriorDesignFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "AIInteriorDesign",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "wand.and.stars",
                          title: "AIInteriorDesign",
                          message: "Redesign a room from a photo in chosen styles."),
                    .init(systemImage: "photo.on.rectangle.angled",
                          title: "Go Pro",
                          message: "Unlimited redesigns, more styles, HD.")
                ],
                presentsPaywallOnFinish: true,
                accent: .purple
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock AIInteriorDesign Pro",
                subheadline: "Unlimited redesigns, more styles, HD.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited redesigns"),
                    .init(systemImage: "bolt.fill", title: "More styles"),
                    .init(systemImage: "nosign", title: "HD")
                ],
                productIDs: ["ai-interior-design_yearly", "ai-interior-design_weekly"],
                highlightedProductID: "ai-interior-design_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .purple, heroSystemImage: "wand.and.stars")
            )
        )
        return AppFactory(config)
    }
}

@main
struct AIInteriorDesignApp: App {
    @StateObject private var factory = AIInteriorDesignFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.purple)
        }
    }
}
